config/routes.rb
Httpizza::Application.routes.draw do

  resources :ingredients
  

  root :to => "static_pages#home"

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/orders/makeline' => 'orders#makeline'
  match '/orders/checkout' => 'orders#checkout'
  match '/orders/confirmation' => 'orders#confirmation'
  match '/orders' => 'orders#create', :via => :post

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  caches_page :index
  
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

end

app/controllers/order_pages_controller.rb
class OrderPagesController < ApplicationController
  caches_page :makeline
  
  def delivery
  end

  def checkout
  end

  def makeline
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  caches_page :makeline
  
  def create
  	respond_to do |format|
  		format.json { render json: params[:order], status: 201 }
  	end
  end

  def confirmation
  end

  def checkout
  end

  def makeline
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "HTTPizza"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ingredient_type %><br />
    <%= f.text_field :ingredient_type %>
  </div>
  <div class="field">
    <%= f.label :icon_image %><br />
    <%= f.text_field :icon_image %>
  </div>
  <div class="field">
    <%= f.label :brush_image %><br />
    <%= f.text_field :brush_image %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Icon image</th>
    <th>Brush image</th>
    <th>Price</th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.name %></td>
    <td><%= ingredient.ingredient_type %></td>
    <td><%= ingredient.icon_image %></td>
    <td><%= ingredient.brush_image %></td>
    <td><%= ingredient.price %></td>
  </tr>
<% end %>
</table>

<br />

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    HTTPizza
    by Christian Orawetz
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "HTTPizza - An HTML5 Showcase", '#', id: "logo", class: "brand" %>
      <nav class="nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<%= render 'layouts/shim' %>

</head>
<body>

	<%= render 'layouts/header' %>

	<div class='container'>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div> <!-- /div.container -->


</body>
</html>

app/views/orders/checkout.html.erb
<% provide(:title, 'Checkout') %>

<h1>Checkout</h1>
<div id="checkout-view" class='row'></div>


<script type="text/template" id="checkout_template">
	<fieldset class="control-group span6">
		<legend>Delivery Information</legend>
		<div>
			<label for="nameField">Name</label>
			<input type="text" id="nameField" placeholder="Enter a name…" required value="<?= order.get('name') ?>"/>
		</div>

		<div>
			<label for="emailField">Email Address</label>
			<input type="email" id="emailField" id="nameField"placeholder="Enter an email address..." required value="<?= order.get('email') ?>"/>
		</div>

		<div>
			<label for="phoneField">Phone Number</label>
			<input type="tel" id="phoneField" placeholder="Enter a phone number..." required value="<?= order.get('phone') ?>"/>
		</div>

		<div>	
			<label for="addressField">Address</label>
			<div>
				<textarea rows="5" id="addressField" placeholder="Enter an address…" required><?= order.get('address') ?></textarea>
				<button class="btn" id="geolocButton">Locate me</button>
			</div>

			<div id="map-canvas" style="width: auto; height: 300px;"></div>
		</div>
	</fieldset>

	<fieldset class='span6'>
		<legend>Order Summary</legend>
		<table class="table table-bordered">
			<tr><th colspan="2">Your Pizza</th></tr>
			<tr>
				<td>Crust:</td>
				<td><?= order.get('pizza').get('crust') ?></td>
			</tr>
			<tr>
				<td>Sauce:</td>
				<td><?= order.get('pizza').get('sauce') ?></td>
			</tr>
			<tr>
				<td>Cheeses:</td>
				<td>
				<? _.each(order.get('pizza').get('cheeses'), function(cheese) { ?>
					<?= cheese ?>,
				<? }) ?>
				</td>
			</tr>
			<tr>
				<td>Toppings:</td>
				<td>
				<? _.each(order.get('pizza').get('toppings'), function(topping) { ?>
					<?= topping ?>,
				<? }) ?>
				</td>
			</tr>
			<tr>
				<td>Price $:</td>
				<td><strong>This one's on the house!</strong></td>
			</tr>
		</table>
		
		<button id="placeOrderButton" class="btn btn-primary btn-large pull-right">Place order</button>
	</fieldset>
</script>

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=true"></script>

<script type='text/javascript'>
$(document).ready(function() {
	// Override the default ERB template style due to conflicts with Rails.
	_.templateSettings = {
	    interpolate: /\<\?\=(.+?)\?\>/g,
	    evaluate: /\<\?(.+?)\?\>/g
	};

	// Create and render the checkout view
	new httpizza.CheckoutView({ el: $('#checkout-view') }).render();
})
</script>

app/views/orders/confirmation.html.erb
<h1>Confirmation</h1>

app/views/orders/delivery.html.erb
<% provide(:title, 'Delivery Information') %>

<h1>Delivery Information</h1>
<p>Find me in app/views/order_pages/delivery.html.erb</p>

app/views/orders/makeline.html.erb
<%= provide(:title, 'Build a Pizza') %>

<h1>Pizza Makeline</h1>

<div id='make-line'>
	<div id='ingredients-view'></div>

	<div id='order-area'>
		<div id='pizza-view'></div>
		<div id='order-ticket-view'></div>
	</div>
</div> <!-- /div.make-line -->

<script type='text/template' id='ingredients_template'>
	<ul id='make-line-ingredients'>
		<? _.each(ingredients, function(ingredient) { ?>
			<li class='btn btn-small' data-ingredient="<?= ingredient.get('ingredient_type') + ':' + ingredient.get('name') ?>">
				<span><?= ingredient.get("name") ?></span>
				<img src='<?= ingredient.get("icon_image") ?>'/>
			</li>
		<? }); ?>
	</ul>
	<ul id='make-line-nav' >
		<li><a id='crustLink' href='#' class='active-link'>Crusts</a></li>
		<li><a id='sauceLink' href='#'>Sauces</a></li>
		<li><a id='cheesesLink' href='#'>Cheeses</a></li>
		<li><a id='toppingsLink' href='#'>Toppings</a></li>
	</ul>
</script>

<script type='text/template' id='pizza_template'>
	<div>
		<canvas id='crust-canvas' height='300px' width='300px'></canvas>
		<canvas id='sauce-canvas' height='300px' width='300px'></canvas>
		<canvas id='cheese-canvas' height='300px' width='300px'></canvas>
		<canvas id='toppings-canvas' height='300px' width='300px'></canvas>
	</div>
</script>

<script type='text/template' id='order_ticket_template'>
	<div id='order-ticket'>
		<h1>Order Ticket</h1>

		<div id='ticket-items'>
		<? _.each(itemGroups, function(itemGroup) { ?>
			<section class='order-ticket-item-group'>
			<h1><?= itemGroup.title ?></h1>
			<ul>
			<? _.each(itemGroup.items, function(item) { ?>
				<li>
					<div class='item-name'><?= item.name ?></div>
					
					<div class='remove-link'>
						<a href='#' data-ingredient="<?= itemGroup.title + ':' + item.name ?>">
							<?= itemGroup.title === 'crust' ? 'Change&nbsp;' : 'Remove'?>
						</a>
					</div>

					<div class='item-price'>...$<?= item.price ?></div>
				</li>
			<? }); ?>
			</ul>
			</section>
		<? }); ?>
		</div>

		<div id='ticket-cost'>
			<label>Total:</label>
			$<?= total.toFixed(2) ?>
		</div>

		<button class="btn btn-mini">Checkout</button>
	</div>


</script>

<script type='text/javascript'>
$(document).ready(function() {
	// Override the default ERB template style due to conflicts with Rails.
	_.templateSettings = {
	    interpolate: /\<\?\=(.+?)\?\>/g,
	    evaluate: /\<\?(.+?)\?\>/g
	};

	// Create an AppRouter and start the app.
	var app = new httpizza.AppRouter();
	Backbone.history.start();
});
</script>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>The HTTPizza app is a demo of various HTML5 features as well as Backbone.js.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h3>Welcome to the HTTPizza App!</h3>
  <br/>
  <p>
  	Click the button to start building your pizza.
  </p>

  <%= link_to "Build a pizza now »", orders_makeline_path, class: "btn btn-large" %>
</div>